<?php

/**
 * @file
 * Contains contact_entity.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function contact_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contact_entity module.
    case 'help.page.contact_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function contact_entity_theme() {
  $theme = [];
  $theme['contact_entity'] = array(
    'render element' => 'elements',
    'file' => 'contact_entity.page.inc',
    'template' => 'contact_entity',
  );
  $theme['contact_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'contact_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function contact_entity_theme_suggestions_contact_entity(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#contact_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'contact_entity__' . $sanitized_view_mode;
  $suggestions[] = 'contact_entity__' . $entity->bundle();
  $suggestions[] = 'contact_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'contact_entity__' . $entity->id();
  $suggestions[] = 'contact_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
